# vim:ft=kitty
#: This is a template that can be used to create new kitty themes.
#: Theme files should start with a metadata block consisting of
#: lines beginning with ##. All metadata fields are optional.

## name: darkvoid
## author: jordan (https://github.com/darkvoid-theme)
## license: UNLICENSE
## upstream: https://github.com/darkvoid-theme/kitty
## blurb: Kitty Colorscheme for dark dwellers with glow effects.

#: All the settings below are colors, which you can choose to modify, or use the
#: defaults. You can also add non-color based settings if needed but note that
#: these will not work with using kitty @ set-colors with this theme. For a
#: reference on what these settings do see https://sw.kovidgoyal.net/kitty/conf/

#: The basic colors

foreground                      #c0c0c0
background                      #1c1c1c
# selection_foreground            #000000
# selection_background            #fffacd


#: Cursor colors

cursor                            #bdfe58
# cursor_text_color               #111111
# cursor_trail_color              none


#: URL underline color when hovering with mouse

# url_color                       #0087bd


#: kitty window border colors and terminal bell colors

active_border_color             #585858
inactive_border_color           #303030
# bell_border_color               #ff5a00
# visual_bell_color               none


#: OS Window titlebar colors

# wayland_titlebar_color          system
macos_titlebar_color              background


#: Tab bar colors

active_tab_foreground   #1bfd9c
active_tab_background   #1c1c1c
inactive_tab_foreground #404040
inactive_tab_background #1c1c1c
tab_bar_background      #1c1c1c
# tab_bar_margin_color            none


#: Colors for marks (marked text in the terminal)

# mark1_foreground black
# mark1_background #98d3cb
# mark2_foreground black
# mark2_background #f2dcd3
# mark3_foreground black
# mark3_background #f274bc

#: The basic 16 colors
#: You can set the remaining 240 colors as color16 to color255.

# black
color0 #1c1c1c
color8 #404040

# red
color1 #e62020
color9 #ffb3ba

# green
color2  #baffc9
color10 #baffc9

# yellow
color3  #ffffba
color11 #ffffba

# blue
color4  #7fa1c3
color12 #7fa1c3

# magenta
color5  #dea6a0
color13 #dea6a0

# cyan
color6  #66b2b2
color14 #66b2b2

# whtie
color7  #c0c0c0
color15 #e6e6e6

# # ANSI colors
# color0  #1c1c1c
# color1  #e62020
# color2  #66b2b2
# color3  #d1d1d1
# color4  #b1b1b1
# color5  #b16286
# color6  #1bfd9c
# color7  #c0c0c0

# # Bright colors
# color8  #404040
# color9  #b2beb5
# color10 #b8bb26
# color11 #bdfe58
# color12 #6a7a8a
# color13 #d3869b
# color14 #b2d8d8
# color15 #ebdbb2
