# vim:ft=kitty
#: This is a template that can be used to create new kitty themes.
#: Theme files should start with a metadata block consisting of
#: lines beginning with ##. All metadata fields are optional.

## name: monium
## author: jordan (https://github.com/NotASentientTomato/public-configs/blob/main/themes/monium_dark/helix/monium_dark.toml)
## license: UNLICENSE
## upstream: https://github.com/NotASentientTomato/public-configs/blob/main/themes/monium_dark/helix/monium_dark.toml
## blurb: Light theme

#: All the settings below are colors, which you can choose to modify, or use the
#: defaults. You can also add non-color based settings if needed but note that
#: these will not work with using kitty @ set-colors with this theme. For a
#: reference on what these settings do see https://sw.kovidgoyal.net/kitty/conf/

#: The basic colors

foreground #333331
background #bababd
# selection_foreground            #000000
# selection_background            #fffacd


#: Cursor colors

cursor                            #3388ea
# cursor_text_color               #111111
# cursor_trail_color              none


#: URL underline color when hovering with mouse

# url_color                       #0087bd


#: kitty window border colors and terminal bell colors

active_border_color             #333331
inactive_border_color           #afafaf
# bell_border_color               #ff5a00
# visual_bell_color               none


#: OS Window titlebar colors

# wayland_titlebar_color          system
macos_titlebar_color              background


#: Tab bar colors

active_tab_foreground   #bababd
active_tab_background   #333331
inactive_tab_foreground #000000
inactive_tab_background #bababd
tab_bar_background      #bababd
tab_bar_margin_color    #bababd


#: Colors for marks (marked text in the terminal)

# mark1_foreground black
# mark1_background #98d3cb
# mark2_foreground black
# mark2_background #f2dcd3
# mark3_foreground black
# mark3_background #f274bc

#: The basic 16 colors
#: You can set the remaining 240 colors as color16 to color255.

# black
color0 #333331
color8 #000000

# red
color1 #a93636
color9 #cc0000

# green
color2  #065905
color10 #065905

# yellow
color3   #dcdc60
color11  #ffff70

# blue
color4  #6666aa
color12 #6666aa

# magenta
color5  #dea6a0
color13 #dea6a0

# cyan
color6  #66b2b2
color14 #66b2b2

# white
color7  #fffffd
color15 #fafaf6

# # ANSI colors
# color0  #1c1c1c
# color1  #e62020
# color2  #66b2b2
# color3  #d1d1d1
# color4  #b1b1b1
# color5  #b16286
# color6  #1bfd9c
# color7  #c0c0c0

# # Bright colors
# color8  #404040
# color9  #b2beb5
# color10 #b8bb26
# color11 #bdfe58
# color12 #6a7a8a
# color13 #d3869b
# color14 #b2d8d8
# color15 #ebdbb2
