# general 
[mgr]
syntect_theme = "~/.dotfiles/config/.config/yazi/darkvoid.xml"
marker_copied   = { fg = "green",   bg = "green" }
marker_cut      = { fg = "red",     bg = "red" }
marker_marked   = { fg = "#333331", bg = "#333331" }
marker_selected = { fg = "cyan",    bg = "cyan" }

cwd = { fg = "#333331", bold = true }
hovered = { bg = "#333331", bold = true }

tab_active   = { fg = "#1bfd9c", bold = true, italic = true }
tab_inactive = { fg = "#585858" }
tab_width    = 1

[tabs]

active = { fg = "#bababd", bg="#333331", bold = true }
inactive = { fg = "#333331", bg="#bababd" }
sep_inner = { open = "▐", close = "▌" }
sep_outer = { open = "", close = "" }


# default bg
count_copied   = { fg = "green", reversed = true } # green
count_cut      = { fg = "red", reversed = true } # red
count_selected = { fg = "cyan", reversed = true } # yellow

border_symbol = "│"
border_style = { fg = "#333331"} # white
title_format = ""

[indicator]
current = { bg = "#3388ea", fg = "#fffffd" }
padding = { open = "▐", close = "▌" }
preview = { reversed = false }

# status-line
[status]
sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }
separator_style = { fg = "reset" } # light bg

perm_type = { fg = "#1bfd9c" } # green
perm_read = { fg = "#1bfd9c" } # yellow
perm_write = { fg = "#1bfd9c" } # red
perm_exec = { fg = "#1bfd9c" } # cyan
perm_sep = { fg = "#585858" } # magenta

progress_label  = { fg = "#8ba4b0", bg = "#363646", bold = true }
progress_normal = { fg = "#363646", bg = "#1f1f28" }
progress_error  = { fg = "#363646", bg = "#1f1f28" }

[mode]
normal_main = { fg = "#c0c0c0", bg = "#1c1c1c" }
normal_alt = { fg = "#c0c0c0", bg = "#1c1c1c" }

# Select mode
select_main = { fg = "#1c1c1c", bg = "#1bfd9c" }
select_alt = { bg = "#1c1c1c", fg = "#1bfd9c" }

# Unset mode
unset_main = { fg = "#1c1c1c", bg = "#1bfd9c" }
unset_alt = { bg = "#1c1c1c", fg = "#1bfd9c" }

[select]
border   = { fg = "#7fb4ca" } # blue
active   = { fg = "#938aa9", bold = true } # magenta
inactive = {}

[input]
border   = { fg = "#333331" }
title    = {}
value    = {}
selected = { reversed = true }

[completion]
border   = { fg = "#7fb4ca" } # blue
active   = { reversed = true }
inactive = {}

[tasks]
border  = { fg = "#7fb4ca" } # blue
title   = {}
hovered = { fg = "#938aa9" } # magenta

[which]
cols = 2
separator = " - "
separator_style = { fg = "#727169" } # darkgrey
mask = { bg = "#16161d" } # dark bg
rest = { fg = "#727169" } # darkgrey
cand = { fg = "#8ba4b0" }
desc = { fg = "#565666" }

[help]
on      = { fg = "#7aa89f" } # cyan
run     = { fg = "#938aa9" } # magenta
desc    = {}
hovered = { reversed = true, bold = true }
footer  = { fg = "#090618", bg = "#c5c9c5" } # white

[notify]
title_info  = { fg = "#87a987" } # green
title_warn  = { fg = "#e6c384" } # yellow
title_error = { fg = "#E46876" } # red

# files
[filetype]
rules = [
    { mime = "image/*", fg = "#66b2b2" },
    { mime = "{audio,video}/*", fg = "#66b2b2" },
    { mime = "application/{,g}zip", fg = "#e1e1e1" },
    { mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#e46876" },
    { mime = "application/{pdf,doc,rtf,vnd.*}", fg = "yellow" },
    { url = "*", is = "link", fg = "#5f5f5d" },
    { url = "*/", is = "link", fg = "#5f5f5d" },
    { url = "*", is = "orphan", fg = "#cc0000" },
    # { url = "*", is = "exec", fg = "#efefed" },
    { url = "*/", fg = "#000000"},
    { url = "*", fg = "#000000"},
]

[icon]

# using nf-md-file-*
#       nf-oct-*    (also seems to work okay)

globs = [
	# { url = "/Users/jorb/Code/github.com/**/*", text = "", fg = "#333331" }
	# { url = ".*rc", text = "󱁼", fg = "#efefed" },
]

dirs  = [
	# { name = ".git", text = "", fg = "#333331" }
]

files = [
	# { name = "Makefile", text = "󰧮", fg = "#efefed" },
	# { name = "makefile", text = "󰧮", fg = "#efefed" },
	# { name = "Justfile", text = "󰧮", fg = "#efefed" },
	# { name = "justfile", text = "󰧮", fg = "#efefed" },
	# { name = "Dockerfile", text = "󰧮", fg = "#efefed" },
	# { name = "Containerfile", text = "󰧮", fg = "#efefed" },
	{ name = "config", text = "󱁼", fg = "#efefed" },
	{ name = "conf", text = "󱁼", fg = "#efefed" },
	{ name = "LICENSE", text = "󱆇", fg = "#efefed" },
	# { name = "LICENSE", text = "󰿃", fg = "#efefed" },
	{ name = "CODE_OF_CONDUCT.md", text = "", fg = "#efefed" },
]

exts  = [
	{ name = "js", text = "󱀫", fg = "#efefed" },
	{ name = "jsx", text = "󱀫", fg = "#efefed" },
	{ name = "ts", text = "󱀫", fg = "#efefed" },
	{ name = "tsx", text = "󱀫", fg = "#efefed" },
	{ name = "lua", text = "󱀫", fg = "#efefed" },
	{ name = "php", text = "󱀫", fg = "#efefed" },
	{ name = "jl", text = "󱀫", fg = "#efefed" },
	{ name = "go", text = "󱀫", fg = "#efefed" },
	{ name = "nu", text = "󱀫", fg = "#efefed" },
	{ name = "r", text = "󱀫", fg = "#efefed" },
	{ name = "vim", text = "󱀫", fg = "#efefed" },
	{ name = "ini", text = "󱁼", fg = "#efefed" },
	{ name = "conf", text = "󱁼", fg = "#efefed" },
	{ name = "config", text = "󱁼", fg = "#efefed" },
	{ name = "json", text = "󱁼", fg = "#efefed" },
	{ name = "yaml", text = "󱁼", fg = "#efefed" },
	{ name = "yml", text = "󱁼", fg = "#efefed" },
	{ name = "toml", text = "󱁼", fg = "#efefed" },
	{ name = "xml", text = "󱁼", fg = "#efefed" },
	{ name = "ron", text = "󱁼", fg = "#efefed" },
	{ name = "neon", text = "󱁼", fg = "#efefed" },
	{ name = "pkl", text = "󱁼", fg = "#efefed" },
	{ name = "tf", text = "󱁼", fg = "#efefed" },
	{ name = "bak", text = "󱋢", fg = "#efefed" },
	{ name = "lock", text = "󱀰", fg = "#efefed" },
	{ name = "md", text = "󰧮", fg = "#efefed" },
	{ name = "csv", text = "󰺥", fg = "#efefed" },
	{ name = "tsv", text = "󰺥", fg = "#efefed" },
	{ name = "db", text = "󱘲", fg = "#efefed" },
]

conds = [
	# Special files
	# { if = "block", text = "", fg = "#ffc107" },
	# { if = "char", text = "", fg = "#ffc107" },
	{ if = "sticky", text = "󱝵", fg = "#ffc107" },
	{ if = "fifo", text = "󱪔", fg = "#ffc107" },
	{ if = "sock", text = "󱪖", fg = "#ffc107" },
	{ if = "orphan", text = "󰩌", fg = "red" },
	{ if = "link", text = "󱅸", fg = "blue" },
	{ if = "dummy", text = "󰷇", fg = "red" },

	# Fallback 
	# { if = "hidden", text = "", fg = "#5f5f5d" },
	{ if = "dir & hidden", text = "󱞞", fg = "#5f5f5d" },
	{ if = "!dir & hidden", text = "󰘓", fg = "#5f5f5d" },
	{ if = "dir", text = "󰉋", fg = "#333331" },
	{ if = "exec", text = "", fg = "#efefed" },
	# { if = "exec", text = "󰑷", fg = "#efefed" },
	{ if = "!dir", text = "󰈤", fg = "#efefed" },
]
