#!/usr/bin/env bash

# /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

brew update
brew install node php yarn nvm jq xsv bat fzf bash bottom glow ripgrep fd stow code-minimap tldr
brew install --HEAD luajit neovim
yarn global add intelephense typescript typescript-language-server awsx

stow vim bash config
bat cache --build
# mkdir ~/.vim/{plugged,undodir}
# cp .bash* ~/
# cp .inputrc ~/
# cp .vimrc ~/
# cp -r .config ~/.config
