#!/usr/bin/env bash

brew update
brew install jq xsv bat fzf bash htop glow ripgrep fd
brew install --HEAD luajit neovim

mkdir ~/.vim/{plugged,undodir}
cp .bash* ~/
cp .inputrc ~/
cp .vimrc ~/
cp -r .config ~/.config
