#!/usr/bin/env bash

# /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

brew update
brew install node php yarn nvm jq xsv bat fzf bash htop glow ripgrep fd stow code-minimap tldr
brew install --HEAD luajit neovim
yarn add -g intelephense typescript typescript-language-server

stow vim bash config
# mkdir ~/.vim/{plugged,undodir}
# cp .bash* ~/
# cp .inputrc ~/
# cp .vimrc ~/
# cp -r .config ~/.config
