#!/bin/bash

source "$CONFIG_DIR/colors.sh"

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

bar=(
  position=top
  height=32
  blur_radius=30
  color=$BAR_COLOR
  topmost=off
  sticky=on
  padding_left=0
  padding_right=0
  corner_radius=10
  y_offset=10
  notch_offset=38
  margin=10
)

default=(
  padding_left=5
  padding_right=5
  background.color=$ITEM_BG_COLOR
  background.corner_radius=10
  label.padding_left=4
  label.padding_right=10
  label.color=$WHITE
  label.font="SF Pro:Semibold:14.0"
  icon.font="SF Pro:Semibold:14.0"
  icon.color=$WHITE
  icon.padding_right=4
)

sketchybar --bar "${bar[@]}"
sketchybar --default "${default[@]}"

# left
source $ITEM_DIR/front_app.sh
source $ITEM_DIR/spaces.sh

# right
source $ITEM_DIR/calendar.sh
source $ITEM_DIR/volume.sh
source $ITEM_DIR/battery.sh
source $ITEM_DIR/memory.sh
source $ITEM_DIR/cpu.sh

# Force all scripts to run the first time (never do this in a script)
sketchybar --update
