# Configuration

# home: ~/.local/state/nap
default_language: go
theme: bw

# Colors

primary_color: "#1bfd9c"
primary_color_subdued: "#303030"
red: "#dea6a0"
bright_red: "#dea6a0"
green: "#baffc9"
bright_green: "#baffc9"
foreground: "#c0c0c0"
background: "#1c1c1c"
black: "#1c1c1c"
gray: "#404040"
white: "#d1d1d1"
