[language-server.biome]

command = "biome"
args = ["lsp-proxy"]

[language-server.eslint]

command = "vscode-eslint-language-server"
args = ["--stdio"]

[language-server.eslint.config]

format = true
nodePath = ""
onIgnoredFiles = "off"
packageManager = "npm"
quiet = false
rulesCustomizations = []
run = "onType"
useESLintClass = false
validate = "on"
codeAction = { disableRuleComment = { enable = true, location = "separateLine" }, showDocumentation = { enable = true } }
codeActionOnSave = { mode = "all" }
experimental = { useFlatConfig = false }
problems = { shortenToSingleLine = false }
workingDirectory = { mode = "auto" }

[[language]]

name = "html"
scope = "text.html.basic"
injection-regex = "html"
file-types = ["html", "htm", "shtml", "xhtml", "xht", "jsp", "asp", "aspx", "jshtm", "volt", "rhtml", "edge"]
language-servers = [ "vscode-html-language-server" ]
auto-format = true
indent = { tab-width = 2, unit = "  " }

[[language]]

name = "javascript"
language-servers = [{ name = "typescript-language-server", except-features = ["format"] }, "biome"]
auto-format = true

[[language]]

name = "typescript"
language-servers = [{ name = "typescript-language-server", except-features = ["format"] }, "biome"]
auto-format = true

[[language]]

name = "tsx"
language-servers = [{ name = "typescript-language-server", except-features = ["format"] }, "biome"]
auto-format = true
