# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = " $username[λ](bold fg:#008b94) "
right_format = "$directory$git_branch$time"
add_newline = false # Warp & left/right do not support newlines well

[time]
format = "[at $time]($style) "
style = "fg:#41505e"
disabled = false

[character]
success_symbol = "[➜](bold green)"

[directory]
format = "[$path]($style) "
style = "fg:240"
truncate_to_repo = false
truncation_length = 1

[username]
format = "[$user](blue) "
show_always = true

[git_branch]
format = "[$symbol $branch]($style) "
symbol = ""
style = "bold green"
